/**
 * @module @conveyor/shared/types
 *
 * Core type definitions for Conveyor.
 * All packages depend on these types — they are the contract.
 */

// ─── Job States ──────────────────────────────────────────────────────────────

export type JobState = 'waiting' | 'delayed' | 'active' | 'completed' | 'failed';

// ─── Job Data (stored in the store) ──────────────────────────────────────────

export interface JobData<T = unknown> {
  /** Unique job ID (generated by the store or provided via jobId option) */
  id: string;

  /** Job name (e.g. "send-email", "process-image") */
  name: string;

  /** Queue this job belongs to */
  queueName: string;

  /** Job payload — generic, typed by the consumer */
  data: T;

  /** Current state in the lifecycle */
  state: JobState;

  /** Number of processing attempts made */
  attemptsMade: number;

  /** Progress (0-100) */
  progress: number;

  /** Return value from successful processing */
  returnvalue: unknown;

  /** Error message if failed */
  failedReason: string | null;

  /** Job options (serialized) */
  opts: JobOptions;

  /** Deduplication key (computed hash or custom key) */
  deduplicationKey: string | null;

  /** Logs appended during processing */
  logs: string[];

  // ─── Timestamps ──────────────────────────────────────────────────────

  createdAt: Date;
  processedAt: Date | null;
  completedAt: Date | null;
  failedAt: Date | null;

  /** When the delayed job should be promoted to waiting */
  delayUntil: Date | null;

  // ─── Locking ─────────────────────────────────────────────────────────

  /** Lock expiration timestamp (null = not locked) */
  lockUntil: Date | null;

  /** Worker ID holding the lock */
  lockedBy: string | null;
}

// ─── Job Options ─────────────────────────────────────────────────────────────

export interface BackoffOptions {
  type: 'fixed' | 'exponential' | 'custom';
  delay: number;
  customStrategy?: (attemptsMade: number) => number;
}

export interface RepeatOptions {
  /** Cron expression (5 or 6 fields) */
  cron?: string;
  /** Interval in ms or human-readable ("5 minutes", "2 hours") */
  every?: number | string;
  /** Max number of repetitions */
  limit?: number;
  startDate?: Date;
  endDate?: Date;
  /** IANA timezone string */
  tz?: string;
}

export interface DeduplicationOptions {
  /** Hash the payload automatically for dedup */
  hash?: boolean;
  /** Custom dedup key */
  key?: string;
  /** TTL for dedup entry in ms */
  ttl?: number;
}

export interface JobOptions {
  // ─── Retry ─────────────────────────────────────────────────────────
  /** Number of attempts (default: 1) */
  attempts?: number;
  backoff?: BackoffOptions;

  // ─── Scheduling ────────────────────────────────────────────────────
  /** Delay before execution in ms or human-readable ("5 minutes") */
  delay?: number | string;
  repeat?: RepeatOptions;

  // ─── Priority & Ordering ───────────────────────────────────────────
  /** Lower = higher priority (default: 0) */
  priority?: number;
  /** LIFO mode: last added = first processed (default: false) */
  lifo?: boolean;

  // ─── Deduplication ─────────────────────────────────────────────────
  deduplication?: DeduplicationOptions;

  // ─── Lifecycle ─────────────────────────────────────────────────────
  /** Remove job on completion: true, false, or max age in ms */
  removeOnComplete?: boolean | number;
  /** Remove job on failure: true, false, or max age in ms */
  removeOnFail?: boolean | number;

  // ─── Timeout ───────────────────────────────────────────────────────
  /** Timeout in ms — job marked failed if exceeded */
  timeout?: number;

  // ─── Identifier ────────────────────────────────────────────────────
  /** Custom job ID (manual dedup) */
  jobId?: string;
}

// ─── Queue Options ───────────────────────────────────────────────────────────

export interface QueueOptions {
  store: StoreInterface;
  defaultJobOptions?: Partial<JobOptions>;
}

// ─── Worker Options ──────────────────────────────────────────────────────────

export interface LimiterOptions {
  /** Max jobs in the duration window */
  max: number;
  /** Duration window in ms */
  duration: number;
}

export interface WorkerOptions {
  store: StoreInterface;
  /** Max concurrent jobs on this worker (default: 1) */
  concurrency?: number;
  /** Max concurrent active jobs across ALL workers (optional) */
  maxGlobalConcurrency?: number;
  limiter?: LimiterOptions;
  /** Lock duration in ms (default: 30_000) */
  lockDuration?: number;
  /** Stalled check interval in ms (default: 30_000) */
  stalledInterval?: number;
}

// ─── Store Events ────────────────────────────────────────────────────────────

export type StoreEventType =
  | 'job:waiting'
  | 'job:active'
  | 'job:completed'
  | 'job:failed'
  | 'job:progress'
  | 'job:stalled'
  | 'job:delayed'
  | 'job:removed'
  | 'queue:drained'
  | 'queue:paused'
  | 'queue:resumed'
  | 'queue:error';

export interface StoreEvent {
  type: StoreEventType;
  queueName: string;
  jobId?: string;
  data?: unknown;
  timestamp: Date;
}

// ─── Queue Events (emitted by Queue/Worker) ──────────────────────────────────

export type QueueEventType =
  | 'waiting'
  | 'active'
  | 'completed'
  | 'failed'
  | 'progress'
  | 'stalled'
  | 'delayed'
  | 'removed'
  | 'drained'
  | 'paused'
  | 'resumed'
  | 'error';

// ─── Fetch Options ───────────────────────────────────────────────────────────

export interface FetchOptions {
  /** LIFO mode: fetch most recently added job first */
  lifo?: boolean;
  /** Filter by job name */
  jobName?: string;
}

// ─── Pause Options ───────────────────────────────────────────────────────────

export interface PauseOptions {
  /** Pause only jobs with this name */
  jobName?: string;
}

// ─── Store Options ──────────────────────────────────────────────────────────

export interface StoreOptions {
  /** Run migrations automatically on connect() (default: true) */
  autoMigrate?: boolean;
}

// ─── Store Interface ─────────────────────────────────────────────────────────

/**
 * The StoreInterface is the contract that all storage backends must implement.
 * The core Queue and Worker classes only interact with this interface.
 */
export interface StoreInterface {
  // ─── Lifecycle ─────────────────────────────────────────────────────
  connect(): Promise<void>;
  disconnect(): Promise<void>;

  // ─── Jobs CRUD ─────────────────────────────────────────────────────
  saveJob(queueName: string, job: Omit<JobData, 'id'>): Promise<string>;
  saveBulk(queueName: string, jobs: Omit<JobData, 'id'>[]): Promise<string[]>;
  getJob(queueName: string, jobId: string): Promise<JobData | null>;
  updateJob(queueName: string, jobId: string, updates: Partial<JobData>): Promise<void>;
  removeJob(queueName: string, jobId: string): Promise<void>;

  // ─── Deduplication ─────────────────────────────────────────────────
  findByDeduplicationKey(queueName: string, key: string): Promise<JobData | null>;

  // ─── Locking / Fetching ────────────────────────────────────────────
  fetchNextJob(
    queueName: string,
    workerId: string,
    lockDuration: number,
    opts?: FetchOptions,
  ): Promise<JobData | null>;
  extendLock(queueName: string, jobId: string, duration: number): Promise<boolean>;
  releaseLock(queueName: string, jobId: string): Promise<void>;

  // ─── Global Concurrency ────────────────────────────────────────────
  getActiveCount(queueName: string): Promise<number>;

  // ─── Queries ───────────────────────────────────────────────────────
  listJobs(
    queueName: string,
    state: JobState,
    start?: number,
    end?: number,
  ): Promise<JobData[]>;
  countJobs(queueName: string, state: JobState): Promise<number>;

  // ─── Delayed Jobs ──────────────────────────────────────────────────
  getNextDelayedTimestamp(queueName: string): Promise<number | null>;
  promoteDelayedJobs(queueName: string, timestamp: number): Promise<number>;

  // ─── Pause/Resume by Job Name ──────────────────────────────────────
  pauseJobName(queueName: string, jobName: string): Promise<void>;
  resumeJobName(queueName: string, jobName: string): Promise<void>;
  getPausedJobNames(queueName: string): Promise<string[]>;

  // ─── Maintenance ───────────────────────────────────────────────────
  getStalledJobs(queueName: string, stalledThreshold: number): Promise<JobData[]>;
  clean(queueName: string, state: JobState, grace: number): Promise<number>;
  drain(queueName: string): Promise<void>;

  // ─── Events ────────────────────────────────────────────────────────
  /**
   * Subscribe to store events. Implementation depends on backend:
   * - Memory: EventEmitter
   * - PostgreSQL: LISTEN/NOTIFY
   * - SQLite: Polling
   */
  subscribe(queueName: string, callback: (event: StoreEvent) => void): void;
  unsubscribe(queueName: string, callback?: (event: StoreEvent) => void): void;
  publish(event: StoreEvent): Promise<void>;
}
