/**
 * @module @conveyor/shared/types
 *
 * Core type definitions for Conveyor.
 * All packages depend on these types — they are the contract.
 */

/** Supported time unit suffixes for human-readable durations. */
export type TimeUnit =
  | 'ms'
  | 'millisecond'
  | 'milliseconds'
  | 's'
  | 'second'
  | 'seconds'
  | 'm'
  | 'minute'
  | 'minutes'
  | 'h'
  | 'hour'
  | 'hours'
  | 'd'
  | 'day'
  | 'days'
  | 'w'
  | 'week'
  | 'weeks';

/**
 * A human-readable duration string (e.g. `"5s"`, `"10 minutes"`, `"2h"`).
 *
 * Accepted formats: `"<number><unit>"` or `"<number> <unit>"`.
 */
export type HumanDuration = `${number}${TimeUnit}` | `${number} ${TimeUnit}`;

/**
 * A schedule expression — human duration with optional `"in"` prefix.
 *
 * Accepted formats: `"5s"`, `"10 minutes"`, `"in 10 minutes"`.
 */
export type ScheduleDelay = HumanDuration | `in ${HumanDuration}`;

/** A delay value — either milliseconds (number) or a human-readable string. */
export type Delay = number | HumanDuration;

/** Possible states of a job in its lifecycle. */
export type JobState =
  | 'waiting'
  | 'waiting-children'
  | 'delayed'
  | 'active'
  | 'completed'
  | 'failed';

/**
 * Record of a single processing attempt for a job.
 * One record is created each time a worker picks up the job.
 */
export interface AttemptRecord {
  /** 1-based attempt number. */
  attempt: number;
  /** When this attempt started processing (ISO 8601). */
  startedAt: string;
  /** When this attempt ended (ISO 8601), or `null` if still running. */
  endedAt: string | null;
  /** Outcome of this attempt. */
  status: 'completed' | 'failed';
  /** Error message if the attempt failed. */
  error: string | null;
  /** Stack trace if the attempt failed. */
  stacktrace: string | null;
  /** Logs produced during this specific attempt. */
  logs: string[];
}

/**
 * The raw data structure stored for each job.
 * This is the shape read from and written to the store.
 *
 * @typeParam T - The type of the job payload.
 */
export interface JobData<T = unknown> {
  /** Unique job ID (generated by the store or provided via jobId option). */
  id: string;

  /** Job name (e.g. `"send-email"`, `"process-image"`). */
  name: string;

  /** Queue this job belongs to. */
  queueName: string;

  /** Job payload — generic, typed by the consumer. */
  data: T;

  /** Current state in the lifecycle. */
  state: JobState;

  /** Number of processing attempts made. */
  attemptsMade: number;

  /** Progress percentage (0–100). */
  progress: number;

  /** Return value from successful processing. */
  returnvalue: unknown;

  /** Error message if failed. */
  failedReason: string | null;

  /** Job options (serialized). */
  opts: JobOptions;

  /** Deduplication key (computed hash or custom key). */
  deduplicationKey: string | null;

  /** Logs appended during processing. */
  logs: string[];

  /** Stack traces accumulated across retry attempts. */
  stacktrace: string[];

  /** When the job was created. */
  createdAt: Date;

  /** When the job started processing. */
  processedAt: Date | null;

  /** When the job completed successfully. */
  completedAt: Date | null;

  /** When the job failed. */
  failedAt: Date | null;

  /** When the delayed job should be promoted to waiting. */
  delayUntil: Date | null;

  /** Lock expiration timestamp (`null` = not locked). */
  lockUntil: Date | null;

  /** Worker ID holding the lock. */
  lockedBy: string | null;

  /** ID of parent job (`null` if standalone). */
  parentId: string | null;

  /** Queue name of parent job (for cross-queue flows). */
  parentQueueName: string | null;

  /** Number of children not yet completed (`0` for leaf/standalone jobs). */
  pendingChildrenCount: number;

  /** When the job was cancelled. */
  cancelledAt: Date | null;

  /** Group ID this job belongs to (`null` if ungrouped). */
  groupId: string | null;

  /** Whether this job has been discarded (no more retries). */
  discarded: boolean;

  /** Per-attempt processing history. */
  attemptLogs: AttemptRecord[];
}

/** Configuration for retry backoff strategies. */
export interface BackoffOptions {
  /** The backoff strategy to use. */
  type: 'fixed' | 'exponential' | 'custom';

  /** Base delay in milliseconds. */
  delay: number;

  /** Custom backoff function, called with the current attempt number. */
  customStrategy?: (attemptsMade: number) => number;
}

/** Configuration for recurring (repeat) jobs. */
export interface RepeatOptions {
  /** Cron expression (5, 6, or 7 fields). */
  cron?: string;

  /** Interval in ms or human-readable (`"5 minutes"`, `"2 hours"`). */
  every?: Delay;

  /** Max number of repetitions. */
  limit?: number;

  /** When to start the first repeat. */
  startDate?: Date;

  /** When to stop repeating. */
  endDate?: Date;

  /** IANA timezone string (e.g. `"America/New_York"`). */
  tz?: string;
}

/** Configuration for job deduplication. */
export interface DeduplicationOptions {
  /** Hash the payload automatically for dedup. */
  hash?: boolean;

  /** Custom dedup key string. */
  key?: string;

  /** TTL for dedup entry in ms. After expiry, a new job can be created. */
  ttl?: number;
}

/** Options passed when adding a job to a queue. */
export interface JobOptions {
  /** Number of attempts before marking as failed (default: 1). */
  attempts?: number;

  /** Backoff strategy for retries. */
  backoff?: BackoffOptions;

  /** Delay before execution in ms or human-readable (`"5 minutes"`). */
  delay?: Delay;

  /** Repeat scheduling configuration. */
  repeat?: RepeatOptions;

  /** Lower number = higher priority (default: 0). */
  priority?: number;

  /** LIFO mode: last added = first processed (default: false). */
  lifo?: boolean;

  /** Deduplication configuration. */
  deduplication?: DeduplicationOptions;

  /** Remove job on completion: `true`, `false`, or max age in ms. */
  removeOnComplete?: boolean | number;

  /** Remove job on failure: `true`, `false`, or max age in ms. */
  removeOnFail?: boolean | number;

  /** Timeout in ms — job marked failed if exceeded. */
  timeout?: number;

  /** Custom job ID (manual dedup). */
  jobId?: string;

  /**
   * Policy when a child job fails.
   * - `'fail'` (default): parent fails immediately when any child fails
   * - `'ignore'`: parent proceeds when remaining children finish (failed ones skipped)
   * - `'remove'`: parent is removed if any child fails
   */
  failParentOnChildFailure?: 'fail' | 'ignore' | 'remove';

  /** Assign this job to a group. */
  group?: GroupOptions;
}

/** Options for assigning a job to a group. */
export interface GroupOptions {
  /** Group identifier (e.g. tenant ID, user ID). */
  id: string;

  /** Maximum number of waiting jobs allowed in this group. Throws on `add()` if exceeded. */
  maxSize?: number;
}

/** Worker-side group configuration. */
export interface GroupWorkerOptions {
  /** Max concurrent active jobs per group (distributed, enforced by the store). */
  concurrency?: number;

  /** Per-group rate limiter (worker-local sliding window). */
  limiter?: LimiterOptions;
}

/** Options for creating a {@linkcode Queue}. */
export interface QueueOptions {
  /** The store backend to use. */
  store: StoreInterface;

  /** Default options applied to all jobs added to this queue. */
  defaultJobOptions?: Partial<JobOptions>;
}

/** Configuration for batch processing. */
export interface BatchOptions {
  /** Number of jobs to collect per batch. */
  size: number;
}

/** Result for a single job within a batch. */
export type BatchResult =
  | { status: 'completed'; value?: unknown }
  | { status: 'failed'; error: Error };

/** Rate limiter configuration for workers. */
export interface LimiterOptions {
  /** Max jobs in the duration window. */
  max: number;

  /** Duration window in ms. */
  duration: number;
}

/** Options for creating a {@linkcode Worker}. */
export interface WorkerOptions {
  /** The store backend to use. */
  store: StoreInterface;

  /** Max concurrent jobs on this worker (default: 1). */
  concurrency?: number;

  /** Max concurrent active jobs across ALL workers (optional). */
  maxGlobalConcurrency?: number;

  /** Rate limiter configuration. */
  limiter?: LimiterOptions;

  /** Lock duration in ms (default: 30_000). */
  lockDuration?: number;

  /** Stalled check interval in ms (default: 30_000). */
  stalledInterval?: number;

  /** Start polling immediately on construction (default: true). Set to false to call start() manually. */
  autoStart?: boolean;

  /** LIFO mode: fetch most recently added job first (default: false). */
  lifo?: boolean;

  /** Batch processing configuration. When set, the worker fetches multiple jobs per cycle. */
  batch?: BatchOptions;

  /** Per-group concurrency and rate limiting configuration. */
  group?: GroupWorkerOptions;
}

/** Event types emitted by the store (used for cross-process pub/sub). */
export type StoreEventType =
  | 'job:waiting'
  | 'job:waiting-children'
  | 'job:active'
  | 'job:completed'
  | 'job:failed'
  | 'job:progress'
  | 'job:stalled'
  | 'job:delayed'
  | 'job:removed'
  | 'queue:drained'
  | 'queue:paused'
  | 'queue:resumed'
  | 'job:cancelled'
  | 'queue:error';

/** An event published through the store's pub/sub mechanism. */
export interface StoreEvent {
  /** The event type. */
  type: StoreEventType;

  /** Which queue this event belongs to. */
  queueName: string;

  /** The job ID related to this event, if any. */
  jobId?: string;

  /** Optional extra data attached to the event. */
  data?: unknown;

  /** When the event occurred. */
  timestamp: Date;
}

/** Event types emitted locally by Queue and Worker via {@linkcode EventBus}. */
export type QueueEventType =
  | 'waiting'
  | 'waiting-children'
  | 'active'
  | 'completed'
  | 'failed'
  | 'progress'
  | 'stalled'
  | 'delayed'
  | 'removed'
  | 'drained'
  | 'cancelled'
  | 'paused'
  | 'resumed'
  | 'error';

/** Options for {@linkcode StoreInterface.fetchNextJob}. */
export interface FetchOptions {
  /** LIFO mode: fetch most recently added job first. */
  lifo?: boolean;

  /** Filter by job name. */
  jobName?: string;

  /** Max concurrent active jobs per group (distributed). */
  groupConcurrency?: number;

  /** Group IDs to exclude from fetching (e.g. rate-limited groups). */
  excludeGroups?: string[];

  /** Global rate limit enforced at the store level across all workers. */
  rateLimit?: {
    /** Max jobs allowed in the duration window. */
    max: number;
    /** Duration window in milliseconds. */
    duration: number;
  };
}

/** Options for {@linkcode Queue.pause} and {@linkcode Queue.resume}. */
export interface PauseOptions {
  /** Pause only jobs with this name. */
  jobName?: string;
}

/** Options for conditional {@linkcode StoreInterface.updateJob} calls. */
export interface UpdateJobOptions {
  /** Only apply the update if the job is currently in one of these states. */
  expectedState?: JobState | JobState[];
}

/**
 * Summary information for a queue, returned by {@linkcode StoreInterface.listQueues}.
 * Includes state counts and metadata to avoid N+1 queries from the dashboard.
 */
export interface QueueInfo {
  /** Queue name. */
  name: string;

  /** Job counts per state. */
  counts: Record<JobState, number>;

  /** Whether the queue is globally paused (`__all__` is in the paused names). */
  isPaused: boolean;

  /** Timestamp of the most recent job activity, or `null` if no jobs exist. */
  latestActivity: Date | null;

  /** Number of jobs with a repeat/cron schedule. */
  scheduledCount: number;
}

/**
 * A single aggregated metrics bucket for a queue/job combination.
 * Stores counts and processing time stats over a time period.
 */
export interface MetricsBucket {
  /** Queue name. */
  queueName: string;
  /** Job name, or `'__all__'` for queue-wide aggregation. */
  jobName: string;
  /** Start of the time bucket. */
  periodStart: Date;
  /** Aggregation granularity. */
  granularity: 'minute' | 'hour';
  /** Number of completed jobs in this bucket. */
  completedCount: number;
  /** Number of failed jobs in this bucket. */
  failedCount: number;
  /** Sum of processing durations in milliseconds. */
  totalProcessMs: number;
  /** Shortest processing duration in this bucket. */
  minProcessMs: number | null;
  /** Longest processing duration in this bucket. */
  maxProcessMs: number | null;
}

/** Options for querying metrics. */
export interface MetricsQueryOptions {
  /** Aggregation granularity. */
  granularity: 'minute' | 'hour';
  /** Start of query range (inclusive). */
  from: Date;
  /** End of query range (inclusive). */
  to: Date;
}

/** Configuration for built-in metrics collection. */
export interface MetricsOptions {
  /** Enable metrics recording in updateJob (default: false). */
  enabled: boolean;
  /** Retention for minute-level buckets in minutes (default: 1440 = 24h). */
  retentionMinutes?: number;
  /** Retention for hour-level buckets in hours (default: 720 = 30d). */
  retentionHours?: number;
}

/** Base options shared by all store implementations. */
export interface StoreOptions {
  /** Run migrations automatically on connect() (default: true). */
  autoMigrate?: boolean;

  /** Called when an event handler throws. Defaults to `console.warn`. */
  onEventHandlerError?: (error: unknown) => void;

  /**
   * Enable built-in metrics collection.
   * Disabled by default — must be explicitly enabled.
   *
   * @example
   * ```ts
   * const store = new MemoryStore({ metrics: { enabled: true } });
   * ```
   */
  metrics?: MetricsOptions;
}

/**
 * The contract that all storage backends must implement.
 * The core Queue and Worker classes only interact with this interface.
 */
export interface StoreInterface {
  /** Initialize the store connection and run migrations if configured. */
  connect(): Promise<void>;

  /** Close the store connection and release resources. */
  disconnect(): Promise<void>;

  /**
   * Save a job to the store. If the job has a deduplication key and a
   * matching active job exists, returns the existing job's ID instead.
   *
   * @param queueName - The queue to save the job in.
   * @param job - The job data (without ID — generated by the store).
   * @returns The job ID (new or existing if dedup matched).
   */
  saveJob(queueName: string, job: Omit<JobData, 'id'>): Promise<string>;

  /**
   * Save multiple jobs in a single batch.
   *
   * @param queueName - The queue to save the jobs in.
   * @param jobs - Array of job data (without IDs).
   * @returns Array of job IDs in the same order.
   */
  saveBulk(queueName: string, jobs: Omit<JobData, 'id'>[]): Promise<string[]>;

  /**
   * Retrieve a job by ID.
   *
   * @param queueName - The queue the job belongs to.
   * @param jobId - The job ID.
   * @returns The job data, or `null` if not found.
   */
  getJob(queueName: string, jobId: string): Promise<JobData | null>;

  /**
   * Update specific fields of a job.
   *
   * When `options.expectedState` is provided, the update is applied only if
   * the job's current state matches. Throws {@linkcode InvalidJobStateError}
   * if the state does not match.
   *
   * @param queueName - The queue the job belongs to.
   * @param jobId - The job ID.
   * @param updates - Partial job data to merge.
   * @param options - Optional update constraints.
   */
  updateJob(
    queueName: string,
    jobId: string,
    updates: Partial<JobData>,
    options?: UpdateJobOptions,
  ): Promise<void>;

  /**
   * Remove a job from the store.
   *
   * @param queueName - The queue the job belongs to.
   * @param jobId - The job ID.
   */
  removeJob(queueName: string, jobId: string): Promise<void>;

  /**
   * Find an active job matching a deduplication key (respecting TTL).
   *
   * @param queueName - The queue to search in.
   * @param key - The deduplication key.
   * @returns The matching job, or `null` if none found or TTL expired.
   */
  findByDeduplicationKey(queueName: string, key: string): Promise<JobData | null>;

  /**
   * Atomically fetch and lock the next available job for processing.
   *
   * @param queueName - The queue to fetch from.
   * @param workerId - The worker claiming the job.
   * @param lockDuration - How long to hold the lock (ms).
   * @param opts - Optional fetch options (LIFO, job name filter).
   * @returns The locked job, or `null` if none available.
   */
  fetchNextJob(
    queueName: string,
    workerId: string,
    lockDuration: number,
    opts?: FetchOptions,
  ): Promise<JobData | null>;

  /**
   * Extend the lock on an active job.
   *
   * @param queueName - The queue the job belongs to.
   * @param jobId - The job ID.
   * @param duration - New lock duration from now (ms).
   * @returns `true` if the lock was extended, `false` if the job is no longer active.
   */
  extendLock(queueName: string, jobId: string, duration: number): Promise<boolean>;

  /**
   * Release the lock on a job (set lockUntil and lockedBy to null).
   *
   * @param queueName - The queue the job belongs to.
   * @param jobId - The job ID.
   */
  releaseLock(queueName: string, jobId: string): Promise<void>;

  /**
   * Count currently active (processing) jobs in a queue.
   *
   * @param queueName - The queue to count.
   * @returns The number of active jobs.
   */
  getActiveCount(queueName: string): Promise<number>;

  /**
   * List jobs in a given state with pagination.
   *
   * @param queueName - The queue to query.
   * @param state - Filter by this job state.
   * @param start - Pagination offset (default: 0).
   * @param end - Pagination end (default: 100).
   * @returns Array of matching jobs.
   */
  listJobs(
    queueName: string,
    state: JobState,
    start?: number,
    end?: number,
  ): Promise<JobData[]>;

  /**
   * Count jobs in a given state.
   *
   * @param queueName - The queue to count.
   * @param state - The job state to filter by.
   * @returns The number of matching jobs.
   */
  countJobs(queueName: string, state: JobState): Promise<number>;

  /**
   * Get the earliest delayed job timestamp in a queue.
   *
   * @param queueName - The queue to check.
   * @returns The earliest delay_until timestamp (ms), or `null` if none.
   */
  getNextDelayedTimestamp(queueName: string): Promise<number | null>;

  /**
   * Promote delayed jobs whose delay_until has passed.
   *
   * @param queueName - The queue to promote in.
   * @param timestamp - Current time (ms). Jobs with delay_until <= this are promoted.
   * @returns The number of promoted jobs.
   */
  promoteDelayedJobs(queueName: string, timestamp: number): Promise<number>;

  /**
   * Pause processing of a specific job name (or `"__all__"` for global pause).
   *
   * @param queueName - The queue.
   * @param jobName - The job name to pause.
   */
  pauseJobName(queueName: string, jobName: string): Promise<void>;

  /**
   * Resume processing of a specific job name.
   *
   * @param queueName - The queue.
   * @param jobName - The job name to resume.
   */
  resumeJobName(queueName: string, jobName: string): Promise<void>;

  /**
   * Get the list of currently paused job names.
   *
   * @param queueName - The queue to query.
   * @returns Array of paused job name strings.
   */
  getPausedJobNames(queueName: string): Promise<string[]>;

  /**
   * Detect stalled jobs (active jobs whose lock has expired).
   *
   * @param queueName - The queue to check.
   * @param stalledThreshold - Not used directly; stalled = lock_until < now.
   * @returns Array of stalled jobs.
   */
  getStalledJobs(queueName: string, stalledThreshold: number): Promise<JobData[]>;

  /**
   * Remove old jobs in a terminal state.
   *
   * @param queueName - The queue to clean.
   * @param state - The state to clean (e.g. `"completed"`, `"failed"`).
   * @param grace - Grace period in ms. Only jobs older than this are removed.
   * @returns The number of removed jobs.
   */
  clean(queueName: string, state: JobState, grace: number): Promise<number>;

  /**
   * Remove all waiting and delayed jobs from a queue.
   *
   * @param queueName - The queue to drain.
   */
  drain(queueName: string): Promise<void>;

  /**
   * Subscribe to store events for a queue.
   * Implementation depends on backend (in-memory, LISTEN/NOTIFY, polling).
   *
   * @param queueName - The queue to subscribe to.
   * @param callback - Called for each event.
   */
  subscribe(queueName: string, callback: (event: StoreEvent) => void): void;

  /**
   * Unsubscribe from store events.
   *
   * @param queueName - The queue to unsubscribe from.
   * @param callback - The specific callback to remove, or omit to remove all.
   */
  unsubscribe(queueName: string, callback?: (event: StoreEvent) => void): void;

  /**
   * Publish an event through the store's pub/sub mechanism.
   *
   * @param event - The event to publish.
   */
  publish(event: StoreEvent): Promise<void>;

  /**
   * Save an entire flow tree atomically (children + parent in one transaction).
   * Jobs are inserted in the order provided (children first, then parent).
   *
   * @param jobs - Array of `{ queueName, job }` entries to insert.
   * @returns Array of job IDs in the same order.
   */
  saveFlow(jobs: Array<{ queueName: string; job: Omit<JobData, 'id'> }>): Promise<string[]>;

  /**
   * Called when a child completes; decrements parent's pending counter.
   * If counter reaches 0, transitions parent to `'waiting'`.
   *
   * @param parentQueueName - The queue the parent belongs to.
   * @param parentId - The parent job's ID.
   * @returns The parent's new state after decrement (or `'completed'` if parent was already removed).
   */
  notifyChildCompleted(parentQueueName: string, parentId: string): Promise<JobState>;

  /**
   * Called when a child fails with `'fail'` policy; marks parent as failed.
   *
   * @param parentQueueName - The queue the parent belongs to.
   * @param parentId - The parent job's ID.
   * @param reason - The failure reason string.
   * @returns `true` if the parent was found and updated.
   */
  failParentOnChildFailure(
    parentQueueName: string,
    parentId: string,
    reason: string,
  ): Promise<boolean>;

  /**
   * Get all children of a parent job.
   *
   * @param parentQueueName - The queue the parent belongs to.
   * @param parentId - The parent job's ID.
   * @returns Array of child job data.
   */
  getChildrenJobs(parentQueueName: string, parentId: string): Promise<JobData[]>;

  /**
   * Count active jobs in a specific group.
   *
   * @param queueName - The queue to count in.
   * @param groupId - The group identifier.
   * @returns The number of active jobs in the group.
   */
  getGroupActiveCount(queueName: string, groupId: string): Promise<number>;

  /**
   * Count waiting jobs in a specific group.
   *
   * @param queueName - The queue to count in.
   * @param groupId - The group identifier.
   * @returns The number of waiting jobs in the group.
   */
  getWaitingGroupCount(queueName: string, groupId: string): Promise<number>;

  // ─── Queue Convenience Methods ──────────────────────────────────────

  /**
   * Get job counts for all states in a single call.
   *
   * @param queueName - The queue to count.
   * @returns Record mapping each {@linkcode JobState} to its count.
   */
  getJobCounts(queueName: string): Promise<Record<JobState, number>>;

  /**
   * Destroy a queue and all its data (jobs, paused names, group cursors).
   * Throws if active jobs exist unless `force` is `true`.
   *
   * @param queueName - The queue to obliterate.
   * @param opts - Pass `{ force: true }` to also remove active jobs.
   */
  obliterate(queueName: string, opts?: { force?: boolean }): Promise<void>;

  /**
   * Retry all jobs in a terminal state by moving them back to waiting.
   * Resets attemptsMade, progress, returnvalue, failedReason, failedAt,
   * completedAt, processedAt, and stacktrace.
   *
   * @param queueName - The queue to retry in.
   * @param state - The source state: `'failed'` or `'completed'`.
   * @returns The number of jobs retried.
   */
  retryJobs(queueName: string, state: 'failed' | 'completed'): Promise<number>;

  /**
   * Promote all delayed jobs to waiting immediately, regardless of delay.
   *
   * @param queueName - The queue to promote in.
   * @returns The number of promoted jobs.
   */
  promoteJobs(queueName: string): Promise<number>;

  // ─── Dashboard Methods ─────────────────────────────────────────────

  /**
   * List all known queues with their current state counts and metadata.
   * Used by the dashboard for auto-discovery (no explicit queue list needed).
   *
   * @returns Array of queue info objects.
   */
  listQueues(): Promise<QueueInfo[]>;

  /**
   * Find a job by ID across all queues.
   * Job IDs are UUIDs and unique across the entire store.
   *
   * @param jobId - The job ID to search for.
   * @returns The job data, or `null` if not found.
   */
  findJobById(jobId: string): Promise<JobData | null>;

  /**
   * Cancel an active job by setting its `cancelledAt` timestamp
   * and publishing a `job:cancelled` event. The worker detects the
   * cancellation and aborts the job's processing.
   *
   * @param queueName - The queue the job belongs to.
   * @param jobId - The job ID to cancel.
   * @returns `true` if the job was found and cancelled, `false` otherwise.
   */
  cancelJob(queueName: string, jobId: string): Promise<boolean>;

  /**
   * Query aggregated metrics for a queue.
   * Optional — stores without metrics support may omit this method.
   *
   * @param queueName - The queue to query metrics for.
   * @param options - Granularity and time range.
   * @returns Aggregated metric buckets.
   */
  getMetrics?(queueName: string, options: MetricsQueryOptions): Promise<MetricsBucket[]>;

  /**
   * Aggregate minute-level metrics into hour-level and purge expired data.
   * Called periodically by the dashboard API.
   * Optional — stores without metrics support may omit this method.
   */
  aggregateMetrics?(): Promise<void>;

  /**
   * Search jobs by payload content.
   * Optional — returns matching jobs across all states.
   *
   * @param queueName - The queue to search in.
   * @param query - The search string to match against serialized payload.
   * @param limit - Maximum number of results (default 50).
   * @returns Matching jobs.
   */
  searchByPayload?(queueName: string, query: string, limit?: number): Promise<JobData[]>;
}

/**
 * Observer callbacks for job lifecycle events.
 *
 * @typeParam T - The type of the job payload.
 */
export interface JobObserver<T = unknown> {
  /** Called when the job becomes active. */
  onActive?: (job: JobData<T>) => void;
  /** Called when the job reports progress. */
  onProgress?: (job: JobData<T>, progress: number) => void;
  /** Called when the job completes successfully. */
  onCompleted?: (job: JobData<T>, result: unknown) => void;
  /** Called when the job fails. */
  onFailed?: (job: JobData<T>, error: string) => void;
  /** Called when the job is cancelled. */
  onCancelled?: (job: JobData<T>) => void;
}

/**
 * A node in a flow tree, describing a job and its children.
 *
 * @typeParam T - The type of the job payload.
 */
export interface FlowJob<T = unknown> {
  /** Job name. */
  name: string;
  /** Queue to add the job to. */
  queueName: string;
  /** Job payload. */
  data: T;
  /** Optional job options. */
  opts?: JobOptions;
  /** Child jobs that must complete before this job is processed. */
  children?: FlowJob[];
}

/**
 * Result of adding a flow tree, containing the created Job and its children results.
 *
 * @typeParam T - The type of the job payload.
 */
export interface FlowResult<T = unknown> {
  /** The created job. */
  job: { id: string; name: string; queueName: string; data: T; state: JobState };
  /** Results for child jobs. */
  children?: FlowResult[];
}
